# Настройки пользователей ssh
add_user_flag: false
remove_user_flag: false

# Окрыть порты фаервола (дополнительная инфа в README роли firewall)
firewall_allowed_tcp_ports:
  - 22
  - 80
  - 443
  - 3000 # Grafana
  - 9100 # Node-exporter
  - 9090 # Prometheus

# Настройки доменного имени для хоста мониторинга
grafana_domain: grafana.vektorooo.ru
prometheus_domain: prometheus.vektorooo.ru

  
