---

- name: proxysql
  hosts: localhost
  tasks:

  - name: Add a server
    proxysql_backend_servers:
      login_user: 'admin'
      login_password: 'admin'
      hostname: 127.0.0.1
      state: present
      load_to_runtime: False
      max_connections: 2048
 #     max_replication_lag: 100
      port: 3306
      hostgroup_id: 15
      
 #   when "'app' in group_names"