---

- name: proxysql
  hosts: localhost
  tasks:

  - proxysql_backend_servers:
    login_user: 'admin'
    login_password: 'admin'
    hostname: 'mysql01'
    state: present
    load_to_runtime: False
