---

- name: proxysql
  hosts: localhost
  tasks:

  - name: Save the mysql users config from memory to disk
    community.proxysql.proxysql_manage_config:
      login_user: 'admin'
      login_password: 'admin'
      action: "SAVE"
      config_settings: "MYSQL USERS"
      direction: "FROM"
      config_layer: "MEMORY"