---
- hosts: app
  gather_facts: yes
  roles:
    - role: app
      tags: [app]

- hosts: app
  gather_facts: yes
  vars_files:
    - group_vars/app.yml #В этом файле список портов, которые нужно открыть
  roles:
    - role: firewall

- hosts: 192.168.234.129
  gather_facts: yes
  roles:
    - role: nginx_role
      tags: [nginx]

- hosts: 192.168.234.129
  gather_facts: yes
  roles:
    - role: php_role
      tags: [php]
