---
- hosts: app
  gather_facts: yes
  roles:
    - role: app
      tags: [app]

- hosts: app
  gather_facts: yes
  vars_files:
    - group_vars/app.yml #В этом файле список портов, которые нужно открыть
  roles:
    - role: firewall
      tags: [firewall]

- hosts: app
  roles:
    - role: node-exporter
      tags: [node-exporter]

- hosts: app
  gather_facts: yes
  roles:
    - role: wordpress
      tags: [wordpress]

