---
- hosts: mon
  gather_facts: no
  roles:
    - role: mon
      tags: [mon]

- hosts: mon
  gather_facts: yes
  vars_files:
    - group_vars/mon.yml #В этом файле список портов, которые нужно открыть
  roles:
    - role: firewall
      tags: [firewall]

- hosts: mon
  var_files:
    - vars/mon/prometheus.yml 
  roles:
    - role: prometheus
      tags: [prometheus]

- hosts: mon
  vars_files:
    - roles/mon/vars/main.yml
  roles:
    - role: geerlingguy.nginx
      tags: [mon-nginx]

- hosts: mon
  roles:
    - role: node-exporter
      tags: [node-exporter]

- hosts: mon
  vars_files:
    - vars/mon/blackbox-exporter.yml
  roles:
    - role: blackbox-exporter
      tags: [blackbox-exporter]
      
- hosts: mon
  var_files:
    - vars/mon/grafana.yml
  roles:
    - role: grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: vektorooo2021
      tags: [grafana]
