---
- hosts: mon
  gather_facts: no
  roles:
    - role: mon
      tags: [mon]

- hosts: mon
  gather_facts: yes
  vars_files:
    - group_vars/mon.yml #В этом файле список портов, которые нужно открыть
  roles:
    - role: firewall

- hosts: mon
  roles:
  - prometheus
  vars:
    prometheus_targets:
      node:
              #        - targets: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('regex_replace', '^(.*)$', '\\1:9100') | list }}"
              #          labels:
              #            env: vektoroo

        - targets: "{{ hostvars[groups['app'][0]]['ansible_host'] }}:9100"      
          labels:
            host: app1
        - targets: "{{ hostvars[groups['app'][1]]['ansible_host'] }}:9100"
          labels:
            host: app2
        - targets: "{{ hostvars[groups['sql'][0]]['ansible_host'] }}:9100"
          labels:
            host: sql1
        - targets: "{{ hostvars[groups['sql'][1]]['ansible_host'] }}:9100"
          labels:
            host: sql2
        - targets: "{{ hostvars[groups['sql'][2]]['ansible_host'] }}:9100"
          labels:
            host: sql3
        - targets: "{{ hostvars[groups['mon'][0]]['ansible_host'] }}:9100"
          labels:
            job: mon 

- hosts: mon
  roles:
    - role: mon-nginx

- hosts: mon
  roles:
    - role: node-exporter
