---
- hosts: all
  become: yes
  roles:
  - node-exporter
  tags:
  - node_exporter

- hosts: mon
  roles:
  - prometheus
  vars:
    prometheus:
      node:
      - targets:
        - mon:9100
#        - demo.cloudalchemy.org:9100
        labels:
          env: vektorooo
      prometheus_scrape_jobs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://mon:9100
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 127.0.0.1:9115  # Blackbox exporter.

- hosts: mon
  roles:
    - role: grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin
        grafana_datasources:
         - name: "Prometheus"
           type: "prometheus"
           access: "proxy"
           url: "http://localhost:9090"
           basicAuth: true
           basicAuthUser: "admin"
           basicAuthPassword: "password"
           isDefault: true
           jsonData:
             tlsAuth: false
             tlsAuthWithCACert: false
             tlsSkipVerify: true
        grafana_dashboards:
          - dashboard_id: '1860'
            revision_id: '8'
            datasource: 'Prometheus'
          - dashboard_id: '3662'
            revision_id: '2'
            datasource: 'Prometheus'
