---

#- hosts: localhost
#  roles:
#    - role: prometheus
#      tags: [prometheus]

#- hosts: localhost
#  roles:
#    - role: node-exporter
#      tags: [node-exporter]

#- hosts: localhost
#  roles:
#    - role: blackbox-exporter
#      tags: [blackbox-exporter]
 



#- hosts: localhost 
#  collections:
#    - my_namespace.my_collection

#  tasks:
#    - import_role:
#        name: grafana
  


   
- hosts: localhost
  roles:
    - role: grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin
      tags: [grafana]


#  -name: register: result
#  tasks:
#    - import_role:
#        name: community.grafana.grafana_notification_channel

#    - grafana_notification_channel:
#      uid: telegram
#      name: "telegram BOT"
#      type: telegram
#      telegram_bot_token: "1846747878:AAEpAckXeA4QhJZQCtBz8ahbZSNow6Vw2-s"
#      telegram_chat_id: "-580617722"
#      is_default: yes

