---
- hosts: mon
  gather_facts: no
  roles:
    - role: mon
      tags: [mon]

- hosts: mon
  gather_facts: yes
  vars_files:
    - group_vars/mon.yml #В этом файле список портов, которые нужно открыть
  roles:
    - role: firewall
      tags: [firewall]

- hosts: mon
  roles:
    - role: prometheus
      tags: [prometheus]

- hosts: mon
  roles:
    - role: mon-nginx
      tags: [mon-nginx]

- hosts: mon
  roles:
    - role: node-exporter
      tags: [node-exporter]
