---
- hosts: mon
  gather_facts: no
  roles:
    - role: mon
      tags: [mon]

- hosts: mon
  gather_facts: yes
  vars_files:
    - group_vars/mon.yml #В этом файле список портов, которые нужно открыть
  roles:
    - role: firewall