  GNU nano 4.8                                                                                      app.yml                                                                                                
---
- hosts: app
  gather_facts: yes
  roles:
    - role: nginx_role
      tags: [nginx]

- hosts: app
  gather_facts: yes
  roles:
    - role: php_role
      tags: [php]

