- src: https://github.com/geerlingguy/ansible-role-firewall.git
  version: 2.5.0
  name: firewall

- src: https://github.com/geerlingguy/ansible-role-php.git
  version: 4.6.1
  name: geerlingguy.php

- src: https://github.com/geerlingguy/ansible-role-nginx.git
  version: 3.0.0
  name: geerlingguy.nginx
