---
# tasks file for wordpress

- name: Create a new database with name 'wordpress'
  mysql_db:
    name: wordpress
    state: present
    login_user: '{{ mysql_user }}'
    login_port: 6033
    login_password: '{{ mysql_password }}'
    login_host: "{{ ansible_facts['default_ipv4']['address'] }}"
  when: inventory_hostname == groups['app'][0]


# WordPress Configuration
- name: create /var/www/{{ server_name }} directory for unarchiving
  file:
    path: /var/www/{{ server_name }}
    state: directory


- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ server_name }}"
    remote_src: yes
    creates: "/var/www/{{ server_name }}/wordpress"


- name: stop apache2 (installed with wp)
  systemd:
    state: stopped
    name: apache2
  ignore_errors: yes


- name: disable apache2
  systemd:
    name: apache2
    enabled: no
  ignore_errors: yes


- name: php7.4-fpm
  apt:
    pkg: php7.4-fpm


- name: python3-pip
  apt:
    pkg:
      - python3-pip
    update_cache: yes


- name: install pip-dependenced packets
  pip:
    name: ['pip', 'passlib']
    state: forcereinstall


- name: basic auth user
  htpasswd:
    path: "/var/www/{{ server_name }}/.passwd"
    name: user
    password: user


- name: Set ownership
  file:
    path: "/var/www/{{ server_name }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data


- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type d -exec chmod 750 {} \\;"


- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type f -exec chmod 640 {} \\;"


- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ server_name }}/wordpress/wp-config.php"


- name: Under construction at default location
  copy:
    dest: /var/www/html/index.html
    content: 'Under construction'

