---
# tasks file for firstrun
- name: Install ntp to sync datetime after restore
  apt:
    name: ntp

- name: Restart ntp if it was installed before previous step
  systemd: state=restarted name=ntp

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
