- name: common
  import_tasks: common.yml


- name: manage users
  import_tasks: users.yml


- name: proxysql
  import_tasks: proxysql.yml


- name: archive wordpress dir
  import_tasks: backup.yml

- name: nginx-prometheus-exporter
  import_tasks: nginxe.yml

