---
- name: Download and unpack nginx-prometheus-exporter v0.9.0
  unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.9.0/nginx-prometheus-exporter_0.9.0_linux_amd64.tar.gz
    dest: "/opt"
    remote_src: yes
    creates: "/opt/nginx-prometheus-exporter_0.9.0_linux_amd64/"


- name: Create a symbolic link
  file:
    src: "/opt/nginx-prometheus-exporter_0.9.0_linux_amd64"
    dest: "/opt/nginx-prometheus-exporter"
    state: link


- name: Configure nginx-prometheus-exporter service
  copy:
    dest: /etc/systemd/system/nginx-prometheus-exporter.service
    content: |
      [Unit]
      Description=mysqld exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      Group=root
      Type=simple
      ExecStart=/opt/nginx-prometheus-exporter/nginx-prometheus-exporter \

      [Install]
      WantedBy=multi-user.target


- name: Enable nginx-prometheus-exporter
  systemd:
    name: nginx-prometheus-exporter
    enabled: yes
    state: restarted


