
#- name: get-url
#  get_url:
#    url: https://repo.proxysql.com/ProxySQL/repo_pub_key
#    dest: /tmp/proxysql.key


- name: Add ProxySQL APT signing key
  apt_key:
    state: present
#    file: /tmp/proxysql.key
    url: https://repo.proxysql.com/ProxySQL/repo_pub_key
  become: true


- name: Add ProxySQL APT repository
  apt_repository:
    repo: deb http://repo.proxysql.com/ProxySQL/proxysql-2.2.x/{{ ansible_distribution_release }}/ ./
    state: present


- name: install proxysql
  apt:
    pkg:
      - proxysql
    update_cache: yes


#- name: Copy proxysql.cfg
#  template:
#    src: proxysql.j2
#    dest: /etc/proxysql.cnf


#- name: Init proxy
#  shell: systemctl stop proxysql


#- name: Init proxy
#  shell: systemctl start proxysql-initial


- name: start proxysql service
  systemd: state=restarted name=proxysql


- name: Wait 20 seconds after restart
  pause:
    seconds: 20


- name: proxysql_backend_servers
  proxysql_backend_servers:
    login_user: 'admin'
    login_password: 'admin'
    login_host: '127.0.0.1'
    login_port: 6032
    hostname: '{{ item  }}'
    hostgroup_id: 0
    state: present
    load_to_runtime: yes
    save_to_disk: yes
  with_items:
    - "{{ hostvars[groups['sql'][0]]['ansible-host'] }}"
    - "{{ hostvars[groups['sql'][1]]['ansible-host'] }}"
    - "{{ hostvars[groups['sql'][2]]['ansible-host'] }}"


- name: proxysql_mysql_users
  proxysql_mysql_users:
    login_user: 'admin'
    login_password: 'admin'
    login_host: '127.0.0.1'
    login_port: 6032
    username: 'root1'
    password: '{{ mysql_root_password }}'
    frontend: yes
    backend: yes
    default_hostgroup: 0
    state: present
    load_to_runtime: yes
    save_to_disk: yes
# можно уточнить предполагаемую нагрузку
#    max_connections: 10000
# нужно почитать поглубже про это
#    transaction_persistent: false


#- name: proxysql_replication_hostgroups
#  proxysql_global_variables:
#    login_user: 'admin'
#    login_password: 'admin'
#    login_host: '127.0.0.1'
#    login_port: 6032
##    writer_hostgroup: 1
##    reader_hostgroup: 2
##    state: present
#    save_to_disk: yes


#- name: proxysql_manage_config
#  proxysql_manage_config:
#    login_user: 'admin'
#    login_password: 'admin'
#    login_host: '127.0.0.1'
#    login_port: 6032


#- name: proxysql_global_variables
#  proxysql_global_variables:
#    login_user: 'admin'
#    login_password: 'admin'
#    login_host: '127.0.0.1'
#    login_port: 6032


#  для начала нам пока ненужно (тюнинг)
#- name:  proxysql_query_rules
#   proxysql_query_rules:
#    login_user: 'admin'
#    login_password: 'admin'
#    login_host: '127.0.0.1'
#    login_port: 6032

