- name: Add users into authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/adduser.pub
  when: add_user_flag

- name: Remove users from authorized keys
  authorized_key:
    user: root
    state: absent
    key: '{{ item }}'
  with_file:
    - public_keys/removeuser.pub
  when: remove_user_flag
