- name: Install mc, htop
  apt:
    pkg:
      - mc
      - htop
      - python3-jmespath

- name: Add users into authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public_ssh_keys/adduser.pub
  when: add_user_flag

- name: Remove users from authorized keys
  authorized_key:
    user: root
    state: absent
    key: '{{ item }}'
  with_file:
    - public_ssh_keys/removeuser.pub
  when: remove_user_flag

# Basic auth
  - name: create /var/www/{{ grafana_domain }} directory for unarchiving
  file:
    path: /var/www/{{ grafana_domain }}
    state: directory

  - name: basic auth user
    htpasswd:
      path: "/var/www/{{ grafana_domain }}/.passwd"
      name: user
      password: user
