- name: Install mc, htop
  apt:
    pkg:
      - mc
      - htop
      - python3-jmespath

- name: Add users into authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public_ssh_keys/adduser.pub
  when: add_user_flag

- name: Remove users from authorized keys
  authorized_key:
    user: root
    state: absent
    key: '{{ item }}'
  with_file:
    - public_ssh_keys/removeuser.pub
  when: remove_user_flag
