---
# vars file for app

server_name: "{{ domain_address }}" # тут ваш домен

nginx_vhosts:

  - listen: "80"
    server_name: '{{ prometheus_domain }}'
    root: "/var/www/{{ prometheus_domain}}"
    index: "index.php index.html index.htm"
    error_page: "500 502 503 504  /50x.html"
    access_log: "/var/log/nginx/{{ prometheus_domain }}.access.log  main"
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ prometheus_domain }}.conf"
    extra_parameters: |
      location / {
        proxy_pass http://{{ ansible_host | default('localhost') }}:9090/;
      }
      auth_basic           "Administrator’s Area";
      auth_basic_user_file  "/var/www/{{ prometheus_domain }}/.passwd";
      proxy_set_header X-WEBAUTH-USER $remote_user;
      proxy_set_header Authorization "";

  - listen: "80"
    server_name: '{{ grafana_domain }}'
    root: "/var/www/{{ grafana_domain}}"
    index: "index.php index.html index.htm"
    error_page: "500 502 503 504  /50x.html"
    access_log: "/var/log/nginx/{{ grafana_domain }}.access.log  main"
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ grafana_domain }}.conf"
    extra_parameters: |
      location / {
        proxy_pass http://{{ ansible_host | default('localhost') }}:3000/;
      }
      auth_basic           "Administrator’s Area";
      auth_basic_user_file  "/var/www/{{ grafana_domain }}/.passwd";
      proxy_set_header  X-Real-IP $remote_addr;
      proxy_set_header  X-Forwarded-Proto http;
      proxy_set_header X-WEBAUTH-USER $remote_user;
      proxy_set_header Authorization "";

#nginx_upstreams:
# - name: myapp1
#   servers: {
#
#   }

grafana_address: "0.0.0.0"
grafana_port: 3000
grafana_cap_net_bind_service: true

grafana_url: "http://{{ grafana_address }}:{{ grafana_port }}"
grafana_api_url: "{{ grafana_url }}"

# Alert notification channels to configure
grafana_alert_notifications:
  notifiers:
    - name: "telegram"
      type: "telegram"
      uid: telegram
      is_default: true
      settings:
        bottoken: "1846747878:AAEpAckXeA4QhJZQCtBz8ahbZSNow6Vw2-s"
        chatid: "-537523797"
        uploadImage: true

# Datasources to configure
#grafana_datasources:
#  - name: "Prometheus"
#    type: "prometheus"
#    access: "proxy"
#    url: "localhost:9090"
#    basicAuth: true
#    basicAuthUser: "{{ prometheus_base_user }}"
#    basicAuthPassword: "{{ prometheus_base_password  }}"
#    isDefault: true

grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus.{{ domain_address }}"
    basicAuth: true
    basicAuthUser: "{{ prometheus_base_user }}"
    basicAuthPassword: "{{ prometheus_base_password  }}"
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true
      httpMethod: 'GET'

