---
# vars file for app

server_name: "{{ domain_address }}" # тут ваш домен

nginx_vhosts:
  - listen: "80"
    server_name: '{{ prometheus_domain }}'
    extra_parameters: |
      location / {
        proxy_pass http://{{ ansible_host | default('localhost') }}:9090/;
      }
      auth_basic           "Administrator’s Area";
      auth_basic_user_file  "/var/www/{{ prometheus_domain }}/.passwd";
      proxy_set_header X-WEBAUTH-USER $remote_user;
      proxy_set_header Authorization "";


  - listen: "80"
    server_name: '{{ grafana_domain }}'
    extra_parameters: |
      location / {
        proxy_pass http://{{ ansible_host | default('localhost') }}:3000/;
      }
      auth_basic           "Administrator’s Area";
      auth_basic_user_file  "/var/www/{{ grafana_domain }}/.passwd";
      proxy_set_header  X-Real-IP $remote_addr;
      proxy_set_header  X-Forwarded-Proto http;
      proxy_set_header X-WEBAUTH-USER $remote_user;
      proxy_set_header Authorization "";
